version: "2"
authtoken: 34q1Z03146o23oiJJ2a5idFisCK_MS6aBatRCdhNqUPr2qyx
tunnels:
  backend:
    addr: 8000
    proto: http
    inspect: true
  frontend:
    addr: 3000
    proto: http
    inspect: true
